version : "3.8"

services:
  postgres:
    image: postgres:13-alpine
    networks:
      - app
    restart: always
    container_name: postgres13 
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
        - .env  
    ports: 
        - 5432:5432 
  redis:
    image: redis
    container_name: redis
    networks:
      - app
    command: redis-server --requirepass secret

    container_name: redis-test-task
    ports:
        - 6379:6379
  srv:
    image: docker.io/aince/test-task
    networks:
      - app
    container_name: server
    depends_on:
      - postgres
      - redis
    ports:
      - 6464:6464
    volumes:
      - ./config.json:/app/config.json  
  clickhouse:
    image: yandex/clickhouse-server
    expose:
      - 8123
      - 9000
    ports:
      - 9000:9000
      - 8123:8123
    volumes:
      - ./ch-config.xml:/etc/clickhouse-server/config.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
      - ./ca.crt:/etc/clickhouse-server/ssl/kafka-ca-qa.crt
networks: 
  app:   
volumes:
  pgdata:    
    driver: local